name: project_template

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  calc: ^0.2.1
  manim_web: ^1.2.3
  ml_linalg: ^13.11.31
  vector_math: ^2.1.4

  gmm:
    path: "./gmm"

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.3
